language: objective-c
osx_image: xcode10

before_install:
  - pod repo update
  
script:
  - xcodebuild clean build -sdk iphonesimulator -workspace Numu\ Tracker.xcworkspace -scheme Numu\ Tracker CODE_SIGNING_REQUIRED=NO